projecao/catalog/urls.py
from django.conf.urls import url
from catalog import views

# TEMPLATE TAGGING
app_name = 'catalog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addhouse/$', views.AddHouseForm, name='add_house')
]

projecao/myauth/urls.py
from django.conf.urls import url
from . import views

# TEMPLATE URLS
app_name = 'myauth'

urlpatterns = [
    url(r'^register/$', views.register, name='register'), 
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
]

projecao/projecao/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic import TemplateView

#path('admin/', admin.site.urls),
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^mauth/', include('myauth.urls')),
    url(r'^webpages/', include('webpages.urls')),
    url(r'^catalog/', include('catalog.urls')),
    # url(r'^addhouse', views.add_house, name='add_house')
]

projecao/webpages/urls.py
from django.conf.urls import url
from webpages import views

urlpatterns = [
    url(r'^$', views.index, name='index')
]

projecao/catalog/models.py
from django.db import models

# Create your models here.
# class Address(models.Model):
#     street = models.CharField(max_length=264)
#     number = models.IntegerField()
#     nghhood = models.CharField(max_length=264)
#     cep = models.CharField(max_length=264,unique=True)


class House(models.Model):
    owner_name = models.CharField(max_length=264)
    price = models.FloatField()
    descrition = models.TextField(max_length=500)
    # address = models.ForeignKey(Address, on_delete=models.PROTECT)
    cep = models.PositiveIntegerField()
    street = models.CharField(max_length=256)
    number = models.PositiveIntegerField()

projecao/myauth/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.PROTECT)

    # additional 
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    # portifolio_site = models.URLField(black=True)

    def __str__(self):
        return self.user.username

projecao/webpages/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class WebPage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(WebPage, on_delete=models.PROTECT)
    date = models.DateField()

    def __str__(self):
        return str(self.name)

projecao/catalog/forms.py
from django import forms
from django.core import validators
from catalog.models import House

class AddHouseForm(forms.ModelForm):
     class Meta:
          db_table = 'House'
          managed = True
          verbose_name = 'House'
          model = House
          fields = '__all__'

     # name = forms.CharField()
     # email = forms.EmailField()
     # verify_email = forms.EmailField(label='Enter your email again')
     # text = forms.CharField(widget=forms.Textarea)

     # validate email in forms
     # def clean(self):
     #      all_clean_data = super().clean()
     #      email = all_clean_data['email']
     #      vmail = all_clean_data['verify_email']

     #      if email != vmail:
     #           raise forms.ValidationError("Make sure emails match!")
     # botcacher = forms.CharField(required=False, 
     #                               widget=forms.HiddenInput,
     #                               validators=[validators.MaxLengthValidator(0)])

     # def clean_botcacher(self):
     #      botcacher = self.cleaned_data['botcacher']
     #      if len(botcacher) > 0:
     #           raise forms.ValidationError("GOTCHA BOT!")
     #      return botcacher

projecao/myauth/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    
    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)

projecao/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
# from catalog import forms
from catalog.forms import AddHouseForm

# Create your views here.
def index(request):
    my_dic = {'insert': "This is a insertion!"}
    return render(request, 'catalog/index.html', context=my_dic)

def add_house(request):
    form = AddHouseForm()

    if request == 'POST':
        form = AddHouseForm(request.POST)

    if form.is_valid():
        form.save(commit=True)
        return index(request)
    else:
        print("Form invalid")


#     form = forms.AddHouseForm()

#     if request == 'POST':
#         form = forms.AddHouseForm(request.POST)

#         if form.is_valid():
#             form.save(commit=True)
#             return index(request)
#         else:
#             print("Form invalid")
        
    return render(request, 'catalog/add_house_form.html', {'form':form})

projecao/myauth/views.py
from django.shortcuts import render
from .forms import UserProfileInfoForm, UserForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST) 
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'myauth/registration.html', {'user_form': user_form, 
                                                      'profile_form': profile_form, 
                                                      'registered': registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverve('index'))

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverve('index'))

            else:
                return HttpResponse("Account not active")

        else:
            print("Someone tried to login and failed")
            print("Username: {}".format(username))
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request, 'myauth/login.html', {})

projecao/webpages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from webpages.models import Topic, AccessRecord, WebPage

# Create your views here.
def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}

    return render(request, 'webpages/index.html', context=date_dict)

projecao/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href=" {% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href=" {% static 'css/index.css' %}">
    <!-- Latest compiled and minified JavaScript -->
    <script src="{% static 'fontawesome/js/fontawesome-all.min.js' %}" ></script>
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-primary">
        <!-- Brand -->
        <a class="navbar-brand" href="#">Welcome</a>

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <li class="nav-item active"> <a href="" class="nav-link active">Admin</a> </li>
            <li class="nav-item active"> <a href="{% url 'myauth:register' %}" class="nav-link active">Register</a> </li>
            {% if user.is_authenticated %}
              <li class="nav-item active"> <a href="{% url 'myauth:user_logout' %}" class="nav-link active">Logout</a> </li>
            {% else %}
              <li class="nav-item active"> <a href="{% url 'myauth:user_login' %}" class="nav-link active">Login</a> </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    <div class="container">

        {% block body_block %}
        <!-- Anything inside of this will be inherinted -->
        {% endblock %}

    </div>

    {% include "footer.html" %}

    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

projecao/templates/catalog/add_house_form.html
<!DOCTYPE html>
{% extends "../base.html" %}
    {% block body_block %}
        <h1>Adicione uma casa</h1>

        <div class="container"> 
            <form method="POST">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
            
        </div>
    {% endblock body_block %}

projecao/templates/catalog/index.html
<!DOCTYPE html>
{% extends "../base.html" %}
    {% block blockname %}
        <h1>Welcome to the catalog</h1>
        <a href="{% url 'catalog:add_house' %}">Cadastrar uma nova casa</a>
        <a href="{% url 'admin:index' %}">Admin page</a>
        <a href="{% url 'index' %}">Index</a>
    {% endblock blockname %}

projecao/templates/catalog/search.html
<!DOCTYPE html>
{% extends "../base.html" %}
    {% block blockname %}
        <h1>Welcome to the catalog</h1>
        <a href="{% url 'catalog:add_house' %}">Cadastrar uma nova casa</a>
        <a href="{% url 'admin:index' %}">Admin page</a>
        <a href="{% url 'index' %}">Index</a>
    {% endblock blockname %}

projecao/templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small bg-primary text-white">

    <!-- Footer Elements -->
    <div class="container">
  
      <!-- Grid row-->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-12 py-5 text-center">
          <div class="mb-5 flex-center">
  
            <!-- Facebook -->
            <a class="fb-ic">
              <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic">
              <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!-- Google +-->
            <a class="gplus-ic">
              <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!--Linkedin -->
            <a class="li-ic">
              <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <!--Pinterest-->
            <a class="pin-ic">
              <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
            </a>
          </div>
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row-->
  
    </div>
    <!-- Footer Elements -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright: 
        Projeção Assessoria Financeira | Todos os direitos reservados
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->

projecao/templates/index.html
{% extends "base.html" %}

{% block title %}Projeção Imobiliária{% endblock title %}

{% block body_block %}
  <div class="container-fluid no-padding main_banner"> 
    <div class="row">
      <h1>Traga o seu imóvel para a Projeção!</h1>
    </div>

    <div class="row">
      <form action="">
        <div class="form-group col-md-12">
            <div class="input-group">
                <select id="home_type" class="custom-select col-md-3">
                    <option value="1">Apartamento</option>
                    <option value="2">Casa</option>
                    <option value="3">Chácara</option>
                    <option value="4">Comercial</option>
                </select>
                <input type="text" class="form-control col-md-9" placeholder="Bairro, Endereço, Referência">
            </div>
        </div>
      </form>
    </div>
  </div>
{% endblock body_block %}

projecao/templates/myauth/login.html
{% extends "../base.html" %}
{% block body_block %}
  <div class="jumbotron">
      <h1>Please Login</h1>
      <form action="{% url 'myauth:user_login' %}" method="POST">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Enter username">

          <label for="password">Password</label>
          <input type="password" name="password">

          <input type="submit" class="btn btn-primary" value="Login">
      </form>
  </div>
{% endblock body_block %}

projecao/templates/myauth/registration.html
{% extends "../base.html" %}
<!-- {% load staticfiles %} -->

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registration</h1>
    {% else %}
      <h1>Register here</h1>  
      <h3>Fill the form:</h3>

      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" class="btn btn-primary" value="Register">
      </form>
    {% endif %}
  </div>
{% endblock body_block %}

projecao/templates/webpages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Djando Level two</title>
</head>
<body>
    <h1>Here are your access records!</h1>
    
    <div>
        {% if access_records %}
            <table>
                <thead>
                    <th>Site Name</th>
                    <th>Date Accessed</th>
                </thead>

                {% for acc in access_records %}
                    <tr>
                        <td>{{acc.name}}</td>
                        <td>{{acc.date}}</td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p>NO ACCESS RECORDS!</p>
        {% endif %}
    </div>
</body>
</html>